# Generic yash-rice Hyprland configuration.
source = ~/.config/hypr/profile.conf

exec-once = waybar
exec-once = nm-applet --indicator
exec-once = blueman-applet
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = hyprpaper
exec-once = ~/.config/hypr/scripts/apply-wallpaper.sh
exec-once = udiskie
exec-once = ags run ~/.config/ags/app.tsx

env = XDG_CURRENT_DESKTOP,Hyprland
env = QT_QPA_PLATFORM,wayland
env = QT_QPA_PLATFORMTHEME,qt6ct
env = XCURSOR_SIZE,24
env = GTK_THEME,Adwaita:dark

$mainMod = SUPER

bind = $mainMod, RETURN, exec, ghostty
bind = $mainMod, E, exec, thunar
bind = $mainMod, D, exec, rofi -show drun
bind = $mainMod, X, exec, wlogout --protocol layer-shell
bind = $mainMod SHIFT, S, exec, grim -g "$(slurp)" - | tee ~/Pictures/Screenshots/$(date +%Y-%m-%d_%H-%M-%S).png | wl-copy
bind = $mainMod, P, exec, ~/.config/hypr/scripts/toggle-monitor.sh
bind = $mainMod, W, exec, ~/.config/hypr/scripts/WaybarStyles.sh
bind = $mainMod, SPACE, exec, ~/.config/hypr/scripts/WallpaperSelect.sh

bind = $mainMod, Q, killactive
bind = $mainMod, F, fullscreen
bind = $mainMod SHIFT, SPACE, togglefloating
bind = $mainMod, left, movewindow, l
bind = $mainMod, right, movewindow, r
bind = $mainMod, up, movewindow, u
bind = $mainMod, down, movewindow, d
bind = ALT, left, movefocus, l
bind = ALT, right, movefocus, r
bind = ALT, up, movefocus, u
bind = ALT, down, movefocus, d
bind = $mainMod SHIFT, right, movetoworkspace, +1
bind = $mainMod SHIFT, left, movetoworkspace, -1
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod CTRL, right, workspace, +1
bind = $mainMod CTRL, left, workspace, -1
bindel = , XF86MonBrightnessUp, exec, brightnessctl set +10%
bindel = , XF86MonBrightnessDown, exec, brightnessctl set 10%-
bindel = , XF86AudioRaiseVolume, exec, wpctl set-volume -l 1.25 @DEFAULT_AUDIO_SINK@ 5%+
bindel = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

input {
    kb_layout = us
    follow_mouse = 1
    touchpad { natural_scroll = true }
    sensitivity = 0
}

general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    col.active_border = rgba(ffffffaa)
    col.inactive_border = rgba(444444aa)
    layout = dwindle
}

decoration {
    rounding = 10
    blur { enabled = true; size = 3; passes = 1 }
}

animations { enabled = true }
dwindle { preserve_split = true }
windowrule = fullscreen true, match:class ^(eldenring\\.exe)$

